--DROP TABLE METODOS_PAGOS
CREATE TABLE METODOS_PAGOS
(
	ID_METODO SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	PM_FECHA_REGISTRO  DATETIME DEFAULT GETDATE(),
	METODO_DE_PAGO VARCHAR(50)NOT NULL,
	CONSTRAINT PK_PM PRIMARY KEY(ID_METODO)
)
GO
PRINT('TABLA CREADA')
INSERT INTO METODOS_PAGOS(METODO_DE_PAGO)VALUES('CREDIT-DEBIT CARD')
INSERT INTO METODOS_PAGOS(METODO_DE_PAGO)VALUES('ELECTRONIC TRANSFER')
INSERT INTO METODOS_PAGOS(METODO_DE_PAGO)VALUES('CASH')
GO
--DROP TABLE ESTATUS_VENTAS
CREATE TABLE ESTATUS_VENTAS
(
	ID_EV SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	EV_FECHA_REGISTRO  DATETIME DEFAULT GETDATE(),
	ESTATUS VARCHAR(50)NOT NULL,
	CONSTRAINT PK_SS PRIMARY KEY(ID_EV)
)
GO
PRINT('TABLA CREADA')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Unpaid')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('paid')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Shipped')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Not shipped')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Delivered to Buyer')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Not Delivered because the Buyer was not found')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Cancel')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Returned product')
GO
--DROP TABLE TIPOS_INTERACCIONES
CREATE TABLE TIPOS_INTERACCIONES
(
	ID_TIPO_INTERACCION INT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	INTERACCION VARCHAR(50)NOT NULL,
	CONSTRAINT PK_TIPINT PRIMARY KEY (ID_TIPO_INTERACCION),
)
GO
PRINT('TABLA CREADA')
INSERT INTO TIPOS_INTERACCIONES(INTERACCION)VALUES('Car')
INSERT INTO TIPOS_INTERACCIONES(INTERACCION)VALUES('view')
INSERT INTO TIPOS_INTERACCIONES(INTERACCION)VALUES('Purchased')

--DROP TABLE CAT_SEPOMEX
CREATE TABLE CAT_SEPOMEX
(
	ID_ENTIDAD BIGINT,--IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	LOCALIDAD VARCHAR(MAX),
	MUNICIPIO VARCHAR(MAX),
	ESTADO VARCHAR(MAX),
	CIUDAD VARCHAR(MAX),
	CP VARCHAR(100)
	CONSTRAINT PK_ENT PRIMARY KEY (ID_ENTIDAD)
)
GO
PRINT('TABLA CREADA')
--DROP TABLE CATEGORIA_PRODUCTOS
CREATE TABLE CATEGORIA_PRODUCTOS
(
	ID_CATE INT IDENTITY(1,1) NOT FOR REPLICATION,
	CLAVE_CATEGORIA_PRODUCTO VARCHAR(50),
	SKU VARCHAR(50),
	PC_FECHA_REGISTRO  DATETIME DEFAULT GETDATE(),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	CATEGORIA_PRODUCTO VARCHAR(50) UNIQUE NOT NULL,
	CONSTRAINT PK_PC PRIMARY KEY (ID_CATE)
)
GO
PRINT('TABLA CREADA')
--DROP TABLE CLIENTES
CREATE TABLE CLIENTES
(
	ID_CLIENTE BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	IDENTIFIER_CLI VARCHAR(50) UNIQUE,
	CPN_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	USUARIO VARCHAR(20)NOT NULL,
	NOMBRE VARCHAR(100)NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	CONSTRAINT CH_EA CHECK(EMAIL LIKE '%@%'),
	CONSTRAINT PK_CS PRIMARY KEY(ID_CLIENTE)
)
GO
PRINT('TABLA CREADA')
--DROP TABLE PROVEEDORES
CREATE TABLE PROVEEDORES
(
	ID_PROVEEDOR BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	IDENTIFIER_VEND VARCHAR(50) UNIQUE,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	VENDEDOR VARCHAR(100)NOT NULL,
	EMAIL VARCHAR(50) UNIQUE ,
	CONSTRAINT CH_SEA CHECK(EMAIL LIKE '%@%.%'),
	CONSTRAINT PK_SEL PRIMARY KEY(ID_PROVEEDOR)
)
GO
PRINT('TABLA CREADA')
--DROP TABLE PRODUCTOS
CREATE TABLE PRODUCTOS
(
	ID_PRODUCT INT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	IDENTIFIER_PROD VARCHAR(500),
	SKU VARCHAR(500), 
	P_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	PRODUCTO VARCHAR(100)NOT NULL,	
	CANTIDAD_DISPONIBLE DECIMAL(9,2)NOT NULL,
	TAMANHO VARCHAR(50)NOT NULL,
	MARCA VARCHAR(500)NOT NULL,
	PRECIO_UNITARIO DECIMAL(9,2)NOT NULL,
	STYLE VARCHAR(50),
	FK_CATEGORIA_PRODUCTO INT,
	CONSTRAINT CH_PRICE CHECK(PRECIO_UNITARIO>0.0),
	CONSTRAINT PK_PRD0 PRIMARY KEY (ID_PRODUCT),
	CONSTRAINT FK_WH FOREIGN KEY(FK_CATEGORIA_PRODUCTO) REFERENCES CATEGORIA_PRODUCTOS(ID_CATE) ON DELETE SET NULL
)
--ALTER TABLE PRODUCTOS ALTER COLUMN IDENTIFIER_PROD VARCHAR(500) NULL
GO
PRINT('TABLA CREADA')
--DROP TABLE PROVEDORES_PRODUCTOS
CREATE TABLE PROVEEDORES_PRODUCTOS
(
	ID_VEND_PROD BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	FK_ID_VENDEDOR BIGINT,
	FK_ID_PROD INT,
	CONSTRAINT PK_VENDPRD PRIMARY KEY (ID_VEND_PROD),
	CONSTRAINT FK_VENDP FOREIGN KEY(FK_ID_VENDEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR) ON DELETE NO ACTION,
	CONSTRAINT FK_PV FOREIGN KEY(FK_ID_PROD) REFERENCES PRODUCTOS(ID_PRODUCT) ON DELETE NO ACTION
)
GO
PRINT('TABLA CREADA')
--INFO ABOUT SALES
--DROP TABLE ORDENES_VENTA
CREATE TABLE ORDENES_VENTA
(
	"INDEX" BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	"ASIN" VARCHAR(50) UNIQUE,
	ORDER_ID VARCHAR(50) UNIQUE,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
	FECHA_ORDEN_VENTA DATE NOT NULL,
	FULFILMENT_QUIENCUMPLE VARCHAR(50), 
	CANAL_VENTA VARCHAR(50),
	COURIER_STATUS VARCHAR(50),	
	FK_STATUS_VENTA SMALLINT,
	FK_METODO_PAGO SMALLINT,
	CONSTRAINT PK_SALE PRIMARY KEY("INDEX"),		
	CONSTRAINT FK_SSS FOREIGN KEY(FK_STATUS_VENTA) REFERENCES ESTATUS_VENTAS(ID_EV) ON DELETE SET NULL,
	CONSTRAINT FK_PM FOREIGN KEY(FK_METODO_PAGO) REFERENCES METODOS_PAGOS(ID_METODO) ON DELETE SET NULL
)
GO
PRINT('TABLA CREADA')
--DROP TABLE DETALLE_ORDENES
CREATE TABLE DETALLE_ORDENES
(
	ID_ORDEN_DETALLE BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	CANTIDAD_VENTA DECIMAL(9,2)NOT NULL,
	MONTO_VENTA DECIMAL(9,2)NOT NULL,
	MONEDA VARCHAR(30)NOT NULL,
	PROMOTION_IDS VARCHAR(MAX),
	FK_ORDEN BIGINT,
	FK_CLIENTE BIGINT,
	FK_PRODUCT INT,		
	CONSTRAINT CH_AMOUNT CHECK(MONTO_VENTA>0.0),
	CONSTRAINT PK_DET PRIMARY KEY(ID_ORDEN_DETALLE),
	CONSTRAINT FK_ORD FOREIGN KEY(FK_ORDEN) REFERENCES ORDENES_VENTA("INDEX")ON DELETE NO ACTION,
	CONSTRAINT FK_CL FOREIGN KEY(FK_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE) ON DELETE NO ACTION,
	CONSTRAINT FK_PR FOREIGN KEY(FK_PRODUCT) REFERENCES PRODUCTOS(ID_PRODUCT)ON DELETE NO ACTION
)
GO
PRINT('TABLA CREADA')
--DROP TABLE INFO_ENTREGAS
CREATE TABLE INFO_ENTREGAS
(
	ID_INFO_ENTREGA BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	DIRECCION_FULL VARCHAR(300) ,
	FK_SEPOMEX BIGINT,
	FK_VENTA BIGINT,
	CONSTRAINT PK_DELIVERY PRIMARY KEY (ID_INFO_ENTREGA),
	CONSTRAINT FK_SALDEL FOREIGN KEY(FK_VENTA)REFERENCES ORDENES_VENTA("INDEX")ON DELETE NO ACTION,
	CONSTRAINT FK_SEPO FOREIGN KEY(FK_SEPOMEX)REFERENCES CAT_SEPOMEX(ID_ENTIDAD)ON DELETE NO ACTION
)
GO
PRINT('TABLA CREADA')
--DROP TABLE ENTREGAS
CREATE TABLE ENTREGAS
(
	NUMERO_ENTREGA BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	ENTREGA_ID VARCHAR(50) UNIQUE DEFAULT (CONCAT('ENTREGA',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	ENT_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	FECHA_ENTREGA DATE NOT NULL,	
	FK_ENTREGA_INFO BIGINT,	
	CONSTRAINT FK_ENTREGA1 FOREIGN KEY(FK_ENTREGA_INFO)REFERENCES INFO_ENTREGAS(ID_INFO_ENTREGA)ON DELETE NO ACTION,	
)
GO
PRINT('TABLA CREADA')
--DROP TABLE INTERACCIONES

----------------------INTERACCIONES
CREATE TABLE INTERACCIONES
(
	ID_INTERACCION BIGINT IDENTITY(1,1) NOT FOR REPLICATION,--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
	HORA_INTERACCION DATETIME DEFAULT GETDATE(),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	FK_TIPO_INTERACCION INT,
	FK_PROD INT,
	FK_CLIE BIGINT,
	CONSTRAINT PK_INTER PRIMARY KEY (ID_INTERACCION),
	CONSTRAINT FK_TP1 FOREIGN KEY(FK_TIPO_INTERACCION) REFERENCES TIPOS_INTERACCIONES(ID_TIPO_INTERACCION)ON DELETE SET NULL,
	CONSTRAINT FK_PR1 FOREIGN KEY(FK_PROD) REFERENCES PRODUCTOS(ID_PRODUCT)ON DELETE NO ACTION,
	CONSTRAINT FK_CL1 FOREIGN KEY(FK_CLIE) REFERENCES CLIENTES(ID_CLIENTE)ON DELETE NO ACTION
)
PRINT('TABLA CREADA')



------------------------------------historico


CREATE TABLE HIST_CLIENTES
(
	ID_CLIENTE VARCHAR(1000),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	IDENTIFIER_CLI VARCHAR(1000),
	USUARIO VARCHAR(1000),
	NOMBRE VARCHAR(1000),
	EMAIL VARCHAR(1000)
	,FECHA_REGISTRO DATETIME DEFAULT GETDATE()--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
)
GO
PRINT('TABLA CREADA')
--DROP TABLE PROVEEDORES
CREATE TABLE HIST_PROVEEDORES
(
	ID_PROVEEDOR VARCHAR(1000),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	IDENTIFIER_VEND VARCHAR(1000),
	VENDEDOR VARCHAR(1000),
	EMAIL VARCHAR(1000) 
	,FECHA_REGISTRO DATETIME DEFAULT GETDATE()--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
)
GO
PRINT('TABLA CREADA')
--DROP TABLE PRODUCTOS

--INFO ABOUT SALES
--DROP TABLE ORDENES_VENTA
CREATE TABLE HIST_ORDENES_VENTA
(
	"INDEX" VARCHAR(1000),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	"ASIN" VARCHAR(1000),
	ORDER_ID VARCHAR(1000),	
	FECHA_ORDEN_VENTA VARCHAR(1000),
	FULFILMENT_QUIENCUMPLE VARCHAR(1000), 
	CANAL_VENTA VARCHAR(1000),
	COURIER_STATUS VARCHAR(1000),	
	FK_STATUS_VENTA VARCHAR(1000),
	FK_METODO_PAGO VARCHAR(1000)
	,FECHA_REGISTRO DATETIME DEFAULT GETDATE()--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
)
GO
PRINT('TABLA CREADA')
--DROP TABLE DETALLE_ORDENES
CREATE TABLE HIST_DETALLE_ORDENES
(
	ID_ORDEN_DETALLE VARCHAR(1000),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	CANTIDAD_VENTA VARCHAR(1000)NOT NULL,
	MONTO_VENTA VARCHAR(1000)NOT NULL,
	MONEDA VARCHAR(1000)NOT NULL,
	PROMOTION_IDS VARCHAR(MAX),
	FK_ORDEN VARCHAR(1000),
	FK_CLIENTE VARCHAR(1000),
	FK_PRODUCT VARCHAR(1000)
	,FECHA_REGISTRO DATETIME DEFAULT GETDATE()--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
)
GO
PRINT('TABLA CREADA')
--DROP TABLE INFO_ENTREGAS
CREATE TABLE HIST_INFO_ENTREGAS
(
	ID_INFO_ENTREGA VARCHAR(1000),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	DIRECCION_FULL VARCHAR(300) ,
	FK_SEPOMEX VARCHAR(1000),
	FK_VENTA VARCHAR(1000)
	,FECHA_REGISTRO DATETIME DEFAULT GETDATE()--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
)
GO
PRINT('TABLA CREADA')
--DROP TABLE ENTREGAS
CREATE TABLE HIST_ENTREGAS
(
	NUMERO_ENTREGA VARCHAR(1000),--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO
	FECHA_ENTREGA VARCHAR(1000),	
	FK_ENTREGA_INFO VARCHAR(1000)
	,FECHA_REGISTRO DATETIME DEFAULT GETDATE()--VALOR GENERADO AUTOMATICAMENTE AL MOMENTO DE DARSE UN NUEVO REGISTRO	
)
GO
PRINT('TABLA CREADA')
--DROP TABLE INTERACCIONES

