USE master
GO

--DROP DATABASE AZURE_VENTAS_AMAZON_DUMMY
GO

CREATE DATABASE AZURE_VENTAS_AMAZON_DUMMY


USE AZURE_VENTAS_AMAZON_DUMMY
GO

CREATE TABLE METODOS_PAGOS
(
	ID_METODO SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
	PM_FECHA_REGISTRO  DATETIME DEFAULT GETDATE(),
	METODO_DE_PAGO VARCHAR(50),
	CONSTRAINT PK_PM PRIMARY KEY(ID_METODO)
)
GO
INSERT INTO METODOS_PAGOS(METODO_DE_PAGO)VALUES('CREDIT-DEBIT CARD')
INSERT INTO METODOS_PAGOS(METODO_DE_PAGO)VALUES('ELECTRONIC TRANSFER')
INSERT INTO METODOS_PAGOS(METODO_DE_PAGO)VALUES('CASH')
GO

CREATE TABLE ESTATUS_VENTAS
(
	ID_EV SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
	EV_FECHA_REGISTRO  DATETIME DEFAULT GETDATE(),
	ESTATUS VARCHAR(50) ,
	CONSTRAINT PK_SS PRIMARY KEY(ID_EV)
)
GO

INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Unpaid')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('paid')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Shipped')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Not shipped')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Delivered to Buyer')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Not Delivered because the Buyer was not found')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Cancel')
INSERT INTO ESTATUS_VENTAS(ESTATUS)VALUES('Returned product')
GO

CREATE TABLE CATEGORIA_PRODUCTOS
(
	ID_CATEGORIA_PRODUCTO VARCHAR(50),
	SKU VARCHAR(50),
	PC_FECHA_REGISTRO  DATETIME DEFAULT GETDATE(),
	CATEGORIA_PRODUCTO VARCHAR(50),
	FECHA_REGISTRO DATE DEFAULT GETDATE(),	
	CONSTRAINT PK_PC PRIMARY KEY (ID_CATEGORIA_PRODUCTO)
)
GO

CREATE TABLE CLIENTES
(
	ID_CLIENTE BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_CLI VARCHAR(50) UNIQUE,
	CPN_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	USUARIO VARCHAR(20) ,
	NOMBRE VARCHAR(100) ,
	EMAIL VARCHAR(50) UNIQUE ,
	CONSTRAINT CH_EA CHECK(EMAIL LIKE '%@%.%'),
	CONSTRAINT PK_CS PRIMARY KEY(ID_CLIENTE)
)
GO

CREATE TABLE PROVEDORES
(
	ID_PROVEEDOR BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_VEND VARCHAR(50) UNIQUE,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	VENDEDOR VARCHAR(100) ,
	EMAIL VARCHAR(50) UNIQUE ,
	CONSTRAINT CH_SEA CHECK(EMAIL LIKE '%@%.%'),
	CONSTRAINT PK_SEL PRIMARY KEY(ID_PROVEEDOR)
)
GO

CREATE TABLE PRODUCTOS
(
	ID_PRODUCT INT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_PROD VARCHAR(50) UNIQUE,
	SKU VARCHAR(50), ---QUE EL SKU SE MANEJE POR PRODUCTO O POR CATEGORIA?
	P_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	PRODUCTO VARCHAR(100),	
	CANTIDAD_DISPONIBLE DECIMAL(9,2) ,
	TAMANHO VARCHAR(50) ,
	MARCA VARCHAR(70) ,
	PRECIO_UNITARIO DECIMAL(9,2),
	STYLE VARCHAR(50),
	FK_CATEGORIA_PRODUCTO VARCHAR(50),
	CONSTRAINT PK_PRD0 PRIMARY KEY (ID_PRODUCT),
	CONSTRAINT FK_WH FOREIGN KEY(FK_CATEGORIA_PRODUCTO) REFERENCES CATEGORIA_PRODUCTOS(ID_CATEGORIA_PRODUCTO)
)
GO

CREATE TABLE PROVEDORES_PRODUCTOS
(
	ID_VEND_PROD BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	FK_ID_VENDEDOR BIGINT,
	FK_ID_PROD INT,
	CONSTRAINT PK_VENDPRD PRIMARY KEY (ID_VEND_PROD),
	CONSTRAINT FK_VENDP FOREIGN KEY(FK_ID_VENDEDOR) REFERENCES PROVEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_PV FOREIGN KEY(FK_ID_PROD) REFERENCES PRODUCTOS(ID_PRODUCT)
)
GO

--INFO ABOUT SALES
CREATE TABLE ORDENES_VENTA
(
	"INDEX" BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	"ASIN" VARCHAR(50) UNIQUE,
	ORDER_ID VARCHAR(50) UNIQUE,
	FECHA_REGISTRO DATETIME DEFAULT GETDATE(),	
	FECHA_ORDEN_VENTA DATE,
	FULFILMENT_QUIENCUMPLE VARCHAR(50), 
	CANAL_VENTA VARCHAR(50),
	COURIER_STATUS VARCHAR(50),
	FK_STATUS_VENTA SMALLINT,
	FK_METODO_PAGO SMALLINT,
	CONSTRAINT PK_SALE PRIMARY KEY("INDEX"),	
	CONSTRAINT FK_SSS FOREIGN KEY(FK_STATUS_VENTA) REFERENCES ESTATUS_VENTAS(ID_EV),
	CONSTRAINT FK_PM FOREIGN KEY(FK_METODO_PAGO) REFERENCES METODOS_PAGOS(ID_METODO)
)
GO

CREATE TABLE DETALLE_ORDENES
(
	ID_ORDEN_DETALLE BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	CANTIDAD_VENTA DECIMAL(9,2) ,
	MONTO_VENTA DECIMAL(9,2),
	MONEDA VARCHAR(30),
	PROMOTION_IDS VARCHAR(MAX),
	FK_ORDEN BIGINT,
	FK_PRODUCT INT,
	FK_CLIENTE BIGINT,	
	CONSTRAINT CH_AMOUNT CHECK(MONTO_VENTA>0.0),
	CONSTRAINT PK_DET PRIMARY KEY(ID_ORDEN_DETALLE),
	CONSTRAINT FK_ORD FOREIGN KEY(FK_ORDEN) REFERENCES ORDENES_VENTA("INDEX"),
	CONSTRAINT FK_PR FOREIGN KEY(FK_PRODUCT) REFERENCES PRODUCTOS(ID_PRODUCT),
	CONSTRAINT FK_CL FOREIGN KEY(FK_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
)
GO

CREATE TABLE INFO_ENTREGAS
(
	ID_ROW_ENTREGA BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	DIRECCION_FULL VARCHAR(300) ,
	PAIS VARCHAR(50),
	ESTADO VARCHAR(50),
	CIUDAD VARCHAR(50),
	CODIGO_POSTAL CHAR(10),
	FK_VENTA VARCHAR(50),
	CONSTRAINT PK_DELIVERY PRIMARY KEY (ID_ROW_ENTREGA),
	CONSTRAINT FK_SALDEL FOREIGN KEY(FK_VENTA)REFERENCES ORDENES_VENTA("INDEX")
)
GO

CREATE TABLE ENTREGAS
(
	NUMERO_ENTREGA BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	ENTREGA_ID VARCHAR(50) UNIQUE DEFAULT (CONCAT('ENTREGA',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	ENT_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
	FECHA_ENTREGA DATE,
	FK_ENTREGA_INFO BIGINT,	
	CONSTRAINT FK_ENTREGA1 FOREIGN KEY(FK_ENTREGA_INFO)REFERENCES INFO_ENTREGAS(ID_ROW_ENTREGA)	
)
GO

----------------------INTERACCIONES

CREATE TABLE TIPOS_INTERACCIONES
(
	ID_TIPO_INTERACCION INT IDENTITY(1,1) NOT FOR REPLICATION,
	INTERACCION VARCHAR(50),
	CONSTRAINT PK_TIPINT PRIMARY KEY (ID_TIPO_INTERACCION),
)
GO

INSERT INTO TIPOS_INTERACCIONES(INTERACCION)VALUES('Car')
INSERT INTO TIPOS_INTERACCIONES(INTERACCION)VALUES('view')
INSERT INTO TIPOS_INTERACCIONES(INTERACCION)VALUES('Purchased')

GO
CREATE TABLE INTERACCIONES
(
	ID_INTERACCION BIGINT IDENTITY(1,1) NOT FOR REPLICATION,	
	HORA_INTERACCION DATETIME,
	FK_TIPO_INTERACCION INT,
	FK_PROD VARCHAR(50),
	FK_CLIE VARCHAR(50),
	CONSTRAINT PK_INTER PRIMARY KEY (ID_INTERACCION),
	CONSTRAINT FK_TP1 FOREIGN KEY(FK_TIPO_INTERACCION) REFERENCES TIPOS_INTERACCIONES(ID_TIPO_INTERACCION),
	CONSTRAINT FK_PR1 FOREIGN KEY(FK_PROD) REFERENCES PRODUCTOS(IDENTIFIER_PROD),
	CONSTRAINT FK_CL1 FOREIGN KEY(FK_CLIE) REFERENCES CLIENTES(IDENTIFIER_CLI)
)
