USE master
GO

DROP DATABASE ONLINE_SALES
GO

CREATE DATABASE ONLINE_SALES
ON PRIMARY
(
NAME=ONLINE_SALES_MDF,
FILENAME='C:\BD\MSSQLS ONLINE_SALES\ONLINE_SALES_MDF.mdf',
SIZE=500MB,
MAXSIZE=1024MB,
FILEGROWTH=10%
)
LOG ON
(
NAME=ONLINE_SALES_LDF,
FILENAME='C:\BD\MSSQLS ONLINE_SALES\ONLINE_SALES_LDF.ldf',
SIZE=500MB,
MAXSIZE=1024MB,
FILEGROWTH=10%
)
GO

USE ONLINE_SALES
GO

CREATE TABLE PAYMENT_METHODS
(
	ID_PM SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
	PM_CREATE_DATE  DATETIME DEFAULT GETDATE(),
	PAYMENT_METHOD VARCHAR(50),
	ACTIVE SMALLINT DEFAULT 1,
	CONSTRAINT CH_AC CHECK(ACTIVE IN (0,1)),
	CONSTRAINT PK_PM PRIMARY KEY(ID_PM)
)
GO

INSERT INTO PAYMENT_METHODS(PAYMENT_METHOD)VALUES('CREDIT-DEBIT CARD')
INSERT INTO PAYMENT_METHODS(PAYMENT_METHOD)VALUES('ELECTRONIC TRANSFER')
INSERT INTO PAYMENT_METHODS(PAYMENT_METHOD)VALUES('CASH')
GO

CREATE TABLE STATUS_SALES
(
	ID_SS SMALLINT IDENTITY(1,1) NOT FOR REPLICATION,
	PM_CREATE_DATE  DATETIME DEFAULT GETDATE(),
	STATUS_SALE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_SS PRIMARY KEY(ID_SS)
)
GO

INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Unpaid')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('paid')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Shipped')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Not shipped')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Delivered to Buyer')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Not Delivered because the Buyer was not found')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Cancel')
INSERT INTO STATUS_SALES(STATUS_SALE)VALUES('Returned product')
GO

--INFO ABOUT PAYMENT METHODS
CREATE TABLE PAYMENT_CARDS_INFO
(
	ID_CARD BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	PCI_CREATE_DATE  DATETIME DEFAULT GETDATE(),
	CARD_NUMBER VARCHAR(16)NOT NULL,	
	CARD_OWNER_NAME VARCHAR(70),
	DUE_DATE CHAR(5) NOT NULL,
	CVV CHAR(3),
	CONSTRAINT CH_CN CHECK(CARD_NUMBER LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	CONSTRAINT CH_DD CHECK(DUE_DATE LIKE '[0-9][0-9]/[0-9][0-9]'),
	CONSTRAINT CH_CVV CHECK(CVV LIKE '[0-9][0-9][0-9]')
)
GO
--INFO ABOUT PAYMENT METHODS
CREATE TABLE ELECTRONICS_TRANSFERS_INFO
(
	ID_ET BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	ETI_CREATE_DATE  DATETIME DEFAULT GETDATE(),
	ET_ORDER_NUMBER VARCHAR(50) UNIQUE DEFAULT (CONCAT(SUBSTRING(CONVERT(varchar(50),NEWID()),5,9),
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	ISSUING_BANK VARCHAR(50),
	RECEIVING_BANK VARCHAR(50),
	INTERBANK_KEY CHAR(18) NOT NULL,
	PAYMENT_AMOUNT DECIMAL(9,2) NOT NULL,
	CONSTRAINT CH_ETIK CHECK(LEN(INTERBANK_KEY) BETWEEN 16 AND 18),
	CONSTRAINT CH_ETPA CHECK(PAYMENT_AMOUNT>0.0),
	CONSTRAINT PK_ET PRIMARY KEY(ET_ORDER_NUMBER)
)
GO
--INFO ABOUT PAYMENT METHODS
CREATE TABLE CASH_PAYMENT_INFO
(
	ID_CP BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	CPI_CREATE_DATE  DATETIME DEFAULT GETDATE(),
	CP_ORDER_NUMBER VARCHAR(50) UNIQUE DEFAULT (CONCAT(SUBSTRING(CONVERT(varchar(50),NEWID()),5,9),
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	PAY_POINT VARCHAR(50),
	INTERBANK_KEY CHAR(18) NOT NULL,
	PAYMENT_AMOUNT DECIMAL(9,2) NOT NULL,
	CONSTRAINT CH_CPIK CHECK(LEN(INTERBANK_KEY) BETWEEN 16 AND 18),
	CONSTRAINT CH_CPPA CHECK(PAYMENT_AMOUNT>0.0),
	CONSTRAINT PK_CP PRIMARY KEY(CP_ORDER_NUMBER)
)
GO

--EACH CATEGORY CAN HAVE MANY PRODUCTS
CREATE TABLE PRODUCTS_CATEGORY
(
	ID_PRODUCT_CATEGORY INT IDENTITY(1,1) NOT FOR REPLICATION,
	PC_CREATE_DATE  DATETIME DEFAULT GETDATE(),
	CATEGORY_NAME VARCHAR(50),
	CREATION_DATE DATE DEFAULT GETDATE(),
	DATE_LAST_MODIFICATION DATETIME,
	CONSTRAINT PK_PC PRIMARY KEY (ID_PRODUCT_CATEGORY)
)
GO
--EACH CUSTOMERS CAN HAVE MANY PHONE NUMBERS
CREATE TABLE CUSTOMERS_PHONE_NUMBERS
(
	ID_CUST_PHONE BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	CPN_CREATION_DATE DATETIME DEFAULT GETDATE(),
	CPN_DATE_LAST_MODIFICATION DATETIME,
	PHONE_NUMBER VARCHAR(20),			
	ACTIVE SMALLINT DEFAULT 1,
	DEFAULT_IS INT,
	CONSTRAINT CH_DI CHECK(DEFAULT_IS IN (0,1)),
	CONSTRAINT CH_ACCP CHECK(ACTIVE IN (0,1)),
	CONSTRAINT PK_PH PRIMARY KEY(ID_CUST_PHONE)
)
GO
--EACH CUSTOMERS CAN HAVE MANY DELIVERY ADDRESSES
CREATE TABLE CUSTOMERS_DELIVERY_ADDRESSES
(
	ID_DEL_ADDRESS BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	CDA_CREATION_DATE DATETIME DEFAULT GETDATE(),
	CDA_DATE_LAST_MODIFICATION DATETIME,
	FULL_DELIVERY_ADDRESS VARCHAR(300) NOT NULL,	
	COUNTRY VARCHAR(50),
	FROM_STATE VARCHAR(50),
	CITY VARCHAR(50),
	POSTAL_CODE CHAR(5),
	BETWEEN_STREETS VARCHAR(100),	
	COORDINATES VARCHAR(50),	
	ACTIVE SMALLINT DEFAULT 1,
	DEFAULT_IS INT,
	CONSTRAINT CH_DICD CHECK(DEFAULT_IS IN (0,1)),
	CONSTRAINT CH_ACCD CHECK(ACTIVE IN (0,1)),
	CONSTRAINT PK_DA PRIMARY KEY(ID_DEL_ADDRESS)
)
GO
--EACH SELLER CAN HAVE MANY PHONE NUMBERS
CREATE TABLE SELLERS_PHONE_NUMBERS
(
	ID_SEL_PHONE BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	SPN_CREATION_DATE DATETIME DEFAULT GETDATE(),
	SPN_DATE_LAST_MODIFICATION DATETIME,
	PHONE_NUMBER VARCHAR(20),	
	ACTIVE SMALLINT DEFAULT 1,
	DEFAULT_IS INT,
	CONSTRAINT CH_DISP CHECK(DEFAULT_IS IN (0,1)),
	CONSTRAINT CH_ACSP CHECK(ACTIVE IN (0,1)),
	CONSTRAINT PK_SPH PRIMARY KEY(ID_SEL_PHONE)
)
GO
--EACH SELLER CAN HAVE MANY DELIVERY ADDRESSES
CREATE TABLE SELLERS_ADDRESS
(
	ID_SEL_ADDRESS BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	SA_CREATION_DATE DATETIME DEFAULT GETDATE(),
	SA_DATE_LAST_MODIFICATION DATETIME,
	FULL_SELLER_ADDRESS VARCHAR(300) NOT NULL,
	COUNTRY VARCHAR(50),
	FROM_STATE VARCHAR(50),
	CITY VARCHAR(50),
	POSTAL_CODE CHAR(5),
	BETWEEN_STREETS VARCHAR(100),	
	COORDINATES VARCHAR(50),
	ACTIVE SMALLINT DEFAULT 1,
	DEFAULT_IS INT,
	CONSTRAINT CH_SADI CHECK(DEFAULT_IS IN (0,1)),
	CONSTRAINT CH_SAAC CHECK(ACTIVE IN (0,1)),
	CONSTRAINT PK_SADA PRIMARY KEY(ID_SEL_ADDRESS)
)
GO

CREATE TABLE CUSTOMERS
(
	ID_CUSTOMER BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_CUST VARCHAR(50) UNIQUE DEFAULT (CONCAT('CUST',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	CPN_CREATION_DATE DATETIME DEFAULT GETDATE(),
	CPN_DATE_LAST_MODIFICATION DATETIME,
	USER_NAME_CLIENT VARCHAR(20) NOT NULL,
	CUSTOMER_NAME VARCHAR(100) NOT NULL,
	EMAIL_ADDRESS VARCHAR(50) UNIQUE NOT NULL,
	CONSTRAINT CH_EA CHECK(EMAIL_ADDRESS LIKE '%@%.%'),
	CONSTRAINT PK_CS PRIMARY KEY(IDENTIFIER_CUST)
)
GO

CREATE TABLE SELLERS
(
	ID_SELLER BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_SEL VARCHAR(50) UNIQUE DEFAULT (CONCAT('SEL',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	S_CREATION_DATE DATETIME DEFAULT GETDATE(),
	S_DATE_LAST_MODIFICATION DATETIME,
	USER_NAME_CLIENT VARCHAR(20) NOT NULL,
	SELLER_NAME VARCHAR(100) NOT NULL,
	EMAIL_ADDRESS VARCHAR(50) UNIQUE NOT NULL,
	CONSTRAINT CH_SEA CHECK(EMAIL_ADDRESS LIKE '%@%.%'),
	CONSTRAINT PK_SEL PRIMARY KEY(IDENTIFIER_SEL)
)
GO
--JOINING THE CONTACT INFORMATION WITH THE MAIN INFORMATION CUSTOMERS
CREATE TABLE CUSTOMER_CONTACT_INFORMATION
(
	CUST_CONTACT_ID BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	FK_CUST VARCHAR(50),
	FK_CUST_PHONE BIGINT,
	FK_CUST_ADDRESS BIGINT,
	CONSTRAINT PK_CONTACT PRIMARY KEY(CUST_CONTACT_ID),
	CONSTRAINT FK_CUST1 FOREIGN KEY (FK_CUST) REFERENCES CUSTOMERS(IDENTIFIER_CUST),
	CONSTRAINT FK_CP1 FOREIGN KEY (FK_CUST_PHONE) REFERENCES CUSTOMERS_PHONE_NUMBERS(ID_CUST_PHONE),
	CONSTRAINT FK_CA1 FOREIGN KEY (FK_CUST_ADDRESS) REFERENCES CUSTOMERS_DELIVERY_ADDRESSES(ID_DEL_ADDRESS),
)
GO
--JOINING THE CONTACT INFORMATION WITH THE MAIN INFORMATION SELLERS
CREATE TABLE SELLER_CONTACT_INFORMATION
(
	SEL_CONTACT_ID BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	FK_SELLER VARCHAR(50),
	FK_SELL_PHONE BIGINT,
	FK_SELL_ADDRESS BIGINT,
	CONSTRAINT PK_SCONTACT PRIMARY KEY(SEL_CONTACT_ID),
	CONSTRAINT FK_SEL1 FOREIGN KEY (FK_SELLER) REFERENCES SELLERS(IDENTIFIER_SEL),
	CONSTRAINT FK_SP1 FOREIGN KEY (FK_SELL_PHONE) REFERENCES SELLERS_PHONE_NUMBERS(ID_SEL_PHONE),
	CONSTRAINT FK_SA1 FOREIGN KEY (FK_SELL_ADDRESS) REFERENCES SELLERS_ADDRESS(ID_SEL_ADDRESS),
)
GO

CREATE TABLE PRODUCTS
(
	ID_PRODUCT INT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_PROD VARCHAR(50) UNIQUE DEFAULT (CONCAT('PROD',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	P_CREATION_DATE DATETIME DEFAULT GETDATE(),
	P_DATE_LAST_MODIFICATION DATETIME,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	QUANTITY_AVAILABLE DECIMAL(9,2) NOT NULL,
	UNIT_MEASUREMENT VARCHAR(50) NOT NULL,
	TRADEMARK VARCHAR(70) NOT NULL,
	UNIT_PRICE DECIMAL(9,2) NOT NULL,
	FK_PRD_PRODUCT_CATEGORY INT,
	CONSTRAINT PK_PRD0 PRIMARY KEY (IDENTIFIER_PROD),
	CONSTRAINT FK_WH FOREIGN KEY(FK_PRD_PRODUCT_CATEGORY) REFERENCES PRODUCTS_CATEGORY(ID_PRODUCT_CATEGORY)
)
GO
--INFO ABOUT SALES
CREATE TABLE SALES
(
	SALE_NUMBER BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_SALE VARCHAR(50) UNIQUE DEFAULT (CONCAT('SALES',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	SALE_CREATION_DATE DATETIME DEFAULT GETDATE(),
	SALE_DATE_LAST_MODIFICATION DATETIME,
	SALE_QUANTITY DECIMAL(9,2) NOT NULL,
	AMOUNT_SALE DECIMAL(9,2) NOT NULL,
	ESTIMATED_DELIVERY_DATE DATE,
	FK_PRODUCT VARCHAR(50),
	FK_STATUS_SALES SMALLINT,
	FK_DELIVERY_INFO BIGINT,
	FK_SELLER_INFO BIGINT,
	CONSTRAINT CH_AMOUNT CHECK(AMOUNT_SALE>0.0),
	CONSTRAINT PK_SALE PRIMARY KEY(IDENTIFIER_SALE),
	CONSTRAINT FK_PR FOREIGN KEY(FK_PRODUCT) REFERENCES PRODUCTS(IDENTIFIER_PROD),
	CONSTRAINT FK_SS FOREIGN KEY(FK_SELLER_INFO) REFERENCES SELLER_CONTACT_INFORMATION(SEL_CONTACT_ID),	
	CONSTRAINT FK_SSS FOREIGN KEY(FK_STATUS_SALES) REFERENCES STATUS_SALES(ID_SS),
	CONSTRAINT FK_DI FOREIGN KEY(FK_DELIVERY_INFO) REFERENCES CUSTOMER_CONTACT_INFORMATION(CUST_CONTACT_ID)
)
GO

CREATE TABLE PAYMENTS
(
	PAYMENT_NUMBER BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_PAYMENT VARCHAR(50) UNIQUE DEFAULT (CONCAT('PAY',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	PAY_CREATION_DATE DATETIME DEFAULT GETDATE(),
	PAY_DATE_LAST_MODIFICATION DATETIME,
	PAYMENT_AMOUNT DECIMAL(9,2) NOT NULL,
	PAYMENT_DATE DATETIME NOT NULL,
	FK_SALE VARCHAR(50),
	CONSTRAINT CH_PA CHECK(PAYMENT_AMOUNT>0.0),
	CONSTRAINT PK_PS PRIMARY KEY(IDENTIFIER_PAYMENT),
	CONSTRAINT FK_SALE FOREIGN KEY(FK_SALE)REFERENCES SALES(IDENTIFIER_SALE)
)
GO

CREATE TABLE DELIVERYS
(
	DEL_NUMBER BIGINT IDENTITY(1,1) NOT FOR REPLICATION,
	IDENTIFIER_DEL VARCHAR(50) UNIQUE DEFAULT (CONCAT('DEL',
		REPLACE(
		REPLACE(
		REPLACE(
			CONVERT(varchar(50),FORMAT(GETDATE(),'dd/MM/yy hh:mm:ssss'))
			,'/',''),' ',''),':','')
			,SUBSTRING(CONVERT(varchar(50),NEWID()),1,4)
	)),
	DEL_CREATION_DATE DATETIME DEFAULT GETDATE(),
	DEL_DATE_LAST_MODIFICATION DATETIME,
	FK_SALEDEL VARCHAR(50),
	FK_PAYMENT_METHOD SMALLINT,
	CONSTRAINT FK_SALDEL FOREIGN KEY(FK_SALEDEL)REFERENCES SALES(IDENTIFIER_SALE),
	CONSTRAINT FK_PM FOREIGN KEY(FK_PAYMENT_METHOD) REFERENCES PAYMENT_METHODS(ID_PM)
)
GO
