CREATE OR ALTER PROC [dbo].[SP_CLEAN_DATA_VENTAS]
AS
BEGIN 
BEGIN TRY	
	print('-------------------ventas----------------------')
	DECLARE @RANDOM AS BIGINT
	DECLARE CURSOR_DATA_ORDENES CURSOR FOR SELECT DISTINCT FK_ORDEN FROM HIST_DETALLE_ORDENES WHERE FK_ORDEN NOT IN (SELECT "INDEX" FROM ORDENES_VENTA) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')--CONVERT(DATE,FECHA_REGISTRO,103)=CONVERT(DATE,GETDATE(),103)
	OPEN CURSOR_DATA_ORDENES
	FETCH NEXT FROM CURSOR_DATA_ORDENES INTO @RANDOM
	WHILE @@fetch_status=0
	BEGIN

		UPDATE TOP (100) HIST_DETALLE_ORDENES 
		SET FK_ORDEN=(SELECT TOP 1 "INDEX" FROM ORDENES_VENTA WHERE "INDEX" NOT IN(SELECT FK_ORDEN FROM HIST_DETALLE_ORDENES))
		WHERE FK_ORDEN NOT IN (SELECT "INDEX" FROM ORDENES_VENTA)

		FETCH NEXT FROM CURSOR_DATA_ORDENES INTO @RANDOM
	END
	CLOSE CURSOR_DATA_ORDENES
	DEALLOCATE CURSOR_DATA_ORDENES
	print('-------------------info entregas----------------------')
	DECLARE @RANDOM3 AS BIGINT
	DECLARE CURSOR_DATA_INFO CURSOR FOR SELECT DISTINCT FK_VENTA FROM HIST_INFO_ENTREGAS WHERE FK_VENTA NOT IN (SELECT "INDEX" FROM ORDENES_VENTA) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')--CONVERT(DATE,FECHA_REGISTRO,103)=CONVERT(DATE,GETDATE(),103)
	OPEN CURSOR_DATA_INFO
	FETCH NEXT FROM CURSOR_DATA_INFO INTO @RANDOM3
	WHILE @@fetch_status=0
	BEGIN

		UPDATE TOP (100) HIST_INFO_ENTREGAS 
		SET FK_VENTA=(SELECT TOP 1 "INDEX" FROM ORDENES_VENTA WHERE "INDEX" NOT IN(SELECT FK_VENTA FROM HIST_INFO_ENTREGAS))
		WHERE FK_VENTA NOT IN (SELECT "INDEX" FROM ORDENES_VENTA)

		FETCH NEXT FROM CURSOR_DATA_INFO INTO @RANDOM3
	END
	CLOSE CURSOR_DATA_INFO
	DEALLOCATE CURSOR_DATA_INFO
	print('-------------------entregas----------------------')
	DECLARE @RANDOM4 AS BIGINT
	DECLARE CURSOR_DATA_ENTREGAS CURSOR FOR SELECT DISTINCT FK_ENTREGA_INFO FROM HIST_ENTREGAS WHERE FK_ENTREGA_INFO NOT IN (SELECT ID_INFO_ENTREGA FROM INFO_ENTREGAS) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')--CONVERT(DATE,FECHA_REGISTRO,103)=CONVERT(DATE,GETDATE(),103)
	OPEN CURSOR_DATA_ENTREGAS
	FETCH NEXT FROM CURSOR_DATA_ENTREGAS INTO @RANDOM4
	WHILE @@fetch_status=0
	BEGIN

		UPDATE TOP (100) HIST_ENTREGAS 
		SET FK_ENTREGA_INFO=(SELECT TOP 1 ID_INFO_ENTREGA FROM INFO_ENTREGAS WHERE ID_INFO_ENTREGA NOT IN(SELECT DISTINCT FK_ENTREGA_INFO FROM HIST_ENTREGAS))
		WHERE FK_ENTREGA_INFO NOT IN (SELECT ID_INFO_ENTREGA FROM INFO_ENTREGAS)

		FETCH NEXT FROM CURSOR_DATA_ENTREGAS INTO @RANDOM4
	END
	CLOSE CURSOR_DATA_ENTREGAS
	DEALLOCATE CURSOR_DATA_ENTREGAS	
	print('-------------------clientes ventas----------------------')
	DECLARE @RANDOM1 AS BIGINT
	DECLARE CURSOR_DATA_CLIENTES CURSOR FOR SELECT DISTINCT FK_CLIENTE FROM HIST_DETALLE_ORDENES WHERE FK_CLIENTE NOT IN (SELECT ID_CLIENTE FROM CLIENTES) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')--CONVERT(DATE,FECHA_REGISTRO,103)=CONVERT(DATE,GETDATE(),103)
	OPEN CURSOR_DATA_CLIENTES
	FETCH NEXT FROM CURSOR_DATA_CLIENTES INTO @RANDOM1
	WHILE @@fetch_status=0
	BEGIN

		UPDATE TOP (500) HIST_DETALLE_ORDENES 
		SET FK_CLIENTE=(SELECT TOP 1 ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE NOT IN(SELECT FK_CLIENTE FROM HIST_DETALLE_ORDENES))
		WHERE FK_CLIENTE NOT IN (SELECT ID_CLIENTE FROM CLIENTES)

		FETCH NEXT FROM CURSOR_DATA_CLIENTES INTO @RANDOM1
	END
	CLOSE CURSOR_DATA_CLIENTES
	DEALLOCATE CURSOR_DATA_CLIENTES
	print('-------------------productos ventas----------------------')
	DECLARE @RANDOM2 AS BIGINT
	DECLARE CURSOR_DATA_PROD CURSOR FOR SELECT DISTINCT FK_PRODUCT FROM HIST_DETALLE_ORDENES WHERE FK_PRODUCT NOT IN (SELECT ID_PRODUCT FROM PRODUCTOS) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')--CONVERT(DATE,FECHA_REGISTRO,103)=CONVERT(DATE,GETDATE(),103)
	OPEN CURSOR_DATA_PROD
	FETCH NEXT FROM CURSOR_DATA_PROD INTO @RANDOM2
	WHILE @@fetch_status=0
	BEGIN

		UPDATE TOP (1000) HIST_DETALLE_ORDENES 
		SET FK_PRODUCT=(SELECT TOP 1 ID_PRODUCT FROM PRODUCTOS WHERE ID_PRODUCT NOT IN(SELECT FK_PRODUCT FROM HIST_DETALLE_ORDENES))
		WHERE FK_PRODUCT NOT IN (SELECT ID_PRODUCT FROM PRODUCTOS)

		FETCH NEXT FROM CURSOR_DATA_PROD INTO @RANDOM2
	END
	CLOSE CURSOR_DATA_PROD
	DEALLOCATE CURSOR_DATA_PROD
	SELECT 'PROCESO TERMINADO CON EXITO' PROCESO
END TRY
BEGIN CATCH
	SELECT 'PROCESO TERMINADO CON EXITO' PROCESO
END CATCH
END
