CREATE OR ALTER PROC [dbo].[SP_MERGE_DATA]
@TABLENAME VARCHAR(100)=NULL
AS
BEGIN
BEGIN TRY
	IF @TABLENAME='CLIENTES'
	BEGIN
		MERGE CLIENTES AS T2 USING HIST_CLIENTES AS T1
			ON T2.IDENTIFIER_CLI=T1.IDENTIFIER_CLI AND T2.EMAIL=T1.EMAIL
			WHEN NOT MATCHED THEN
			INSERT
			(
				IDENTIFIER_CLI,
				USUARIO,
				NOMBRE,
				EMAIL
			)
			VALUES
			(
				IDENTIFIER_CLI,
				USUARIO,
				NOMBRE,
				EMAIL
			);
	END
	ELSE IF @TABLENAME='PROVEEDORES'
	BEGIN
		MERGE PROVEEDORES AS T2 USING HIST_PROVEEDORES AS T1
			ON T2.IDENTIFIER_VEND=T1.IDENTIFIER_VEND AND T2.EMAIL=T1.EMAIL
			WHEN NOT MATCHED THEN
			INSERT
			(
				IDENTIFIER_VEND,
				VENDEDOR,
				EMAIL
			)
			VALUES
			(
				T1.IDENTIFIER_VEND,
				T1.VENDEDOR,
				T1.EMAIL
			);
	END
	ELSE IF @TABLENAME='ORDENES'
	BEGIN
		MERGE ORDENES_VENTA AS T2 USING HIST_ORDENES_VENTA AS T1
			ON T2."ASIN"=T1."ASIN" AND T2.ORDER_ID=T1.ORDER_ID
			WHEN NOT MATCHED THEN
			INSERT
			(
				"INDEX",
				"ASIN",
				ORDER_ID,
				FECHA_ORDEN_VENTA,
				FULFILMENT_QUIENCUMPLE,
				CANAL_VENTA,
				COURIER_STATUS,
				FK_STATUS_VENTA,
				FK_METODO_PAGO
			)
			VALUES
			(
				T1."INDEX",
				T1."ASIN",
				T1.ORDER_ID,
				T1.FECHA_ORDEN_VENTA,
				T1.FULFILMENT_QUIENCUMPLE,
				T1.CANAL_VENTA,
				T1.COURIER_STATUS,
				CONVERT(INT,T1.FK_STATUS_VENTA),
				CONVERT(INT,T1.FK_METODO_PAGO)
			);
	END
	ELSE IF @TABLENAME='DETALLE'
	BEGIN
		MERGE DETALLE_ORDENES AS T2 USING HIST_DETALLE_ORDENES AS T1
			ON T2.FK_ORDEN=T1.FK_ORDEN AND T2.FK_CLIENTE=T1.FK_CLIENTE AND T2.FK_PRODUCT=T1.FK_PRODUCT
			WHEN NOT MATCHED THEN
			INSERT
			(
				CANTIDAD_VENTA,
				MONTO_VENTA,
				MONEDA,
				PROMOTION_IDS,
				FK_ORDEN,
				FK_CLIENTE,
				FK_PRODUCT
			)
			VALUES
			(
				CONVERT(DECIMAL(9,2),T1.CANTIDAD_VENTA),
				CONVERT(DECIMAL(9,2),T1.MONTO_VENTA),
				T1.MONEDA,
				T1.PROMOTION_IDS,
				CONVERT(INT,T1.FK_ORDEN),
				CONVERT(INT,T1.FK_CLIENTE),
				CONVERT(INT,T1.FK_PRODUCT)
			);
	END
	ELSE IF @TABLENAME='INFO'
	BEGIN
		MERGE INFO_ENTREGAS AS T2 USING HIST_INFO_ENTREGAS AS T1
			ON T2.FK_VENTA=T1.FK_VENTA AND T2.FK_SEPOMEX=T1.FK_SEPOMEX
			WHEN NOT MATCHED THEN
			INSERT
			(
				DIRECCION_FULL,
				FK_SEPOMEX,
				FK_VENTA
			)
			VALUES
			(
				T1.DIRECCION_FULL,
				CONVERT(INT,T1.FK_SEPOMEX),
				CONVERT(INT,T1.FK_VENTA)
			);
	END
	ELSE IF @TABLENAME='ENTREGAS'
	BEGIN
		MERGE ENTREGAS AS T2 USING ENTREGAS AS T1
			ON T2.FECHA_ENTREGA=T1.FECHA_ENTREGA AND T2.FK_ENTREGA_INFO=T1.FK_ENTREGA_INFO
			WHEN NOT MATCHED THEN
			INSERT
			(
				FECHA_ENTREGA,
				FK_ENTREGA_INFO
			)
			VALUES
			(
				T1.FECHA_ENTREGA,
				CONVERT(INT,T1.FK_ENTREGA_INFO)
			);
	END
	SELECT 'PROCESO TERMINADO CON EXITO' PROCESO
END TRY
BEGIN CATCH
	SELECT CONCAT('ERROR DURANTE EL PROCES: ',ERROR_MESSAGE()) ERROR_MERGE
END CATCH
END
