
CREATE OR ALTER PROC [dbo].[SP_MERGE_DATA]
@TABLENAME VARCHAR(100)=NULL
AS
BEGIN
BEGIN TRY	
	IF @TABLENAME='CLIENTES'
	BEGIN
		MERGE CLIENTES AS T2 USING HIST_CLIENTES AS T1
			ON T2.IDENTIFIER_CLI=T1.IDENTIFIER_CLI AND T2.EMAIL=T1.EMAIL
			WHEN NOT MATCHED THEN
			INSERT
			(
				IDENTIFIER_CLI,
				USUARIO,
				NOMBRE,
				EMAIL
			)
			VALUES
			(
				IDENTIFIER_CLI,
				USUARIO,
				NOMBRE,
				EMAIL
			);
	END
	ELSE IF @TABLENAME='PROVEEDORES'
	BEGIN
		MERGE PROVEEDORES AS T2 USING HIST_PROVEEDORES AS T1
			ON T2.IDENTIFIER_VEND=T1.IDENTIFIER_VEND AND T2.EMAIL=T1.EMAIL
			WHEN NOT MATCHED THEN
			INSERT
			(
				IDENTIFIER_VEND,
				VENDEDOR,
				EMAIL
			)
			VALUES
			(
				T1.IDENTIFIER_VEND,
				T1.VENDEDOR,
				T1.EMAIL
			);
	END
	ELSE IF @TABLENAME='ORDENES'
	BEGIN
		DELETE FROM HIST_ORDENES_VENTA WHERE "INDEX"='None' or "ASIN"='None'
		SELECT   ORDER_ID
		INTO DropDuplicate
		FROM HIST_ORDENES_VENTA
		GROUP BY ORDER_ID
		HAVING COUNT(ORDER_ID) > 1		

		DELETE HIST_ORDENES_VENTA
		WHERE ORDER_ID
		IN (SELECT ORDER_ID
		FROM DropDuplicate)
		
		drop table DropDuplicate

		MERGE ORDENES_VENTA AS T2 USING (SELECT * FROM HIST_ORDENES_VENTA WHERE FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')) AS T1
			ON T2."ASIN"=T1."ASIN" AND T2.ORDER_ID=T1.ORDER_ID
			WHEN NOT MATCHED THEN
			INSERT
			(
				"ASIN",
				ORDER_ID,
				FECHA_ORDEN_VENTA,
				FULFILMENT_QUIENCUMPLE,
				CANAL_VENTA,
				COURIER_STATUS,
				FK_STATUS_VENTA,
				FK_METODO_PAGO
			)
			VALUES
			(
				T1."ASIN",
				T1.ORDER_ID,
				CONVERT(DATE, T1.FECHA_ORDEN_VENTA, 103),
				T1.FULFILMENT_QUIENCUMPLE,
				T1.CANAL_VENTA,
				T1.COURIER_STATUS,
				CONVERT(INT,T1.FK_STATUS_VENTA),
				CONVERT(INT,T1.FK_METODO_PAGO)
			);
	END
	ELSE IF @TABLENAME='DETALLE'
	BEGIN
		--EXEC SP_CLEAN_DATA_VENTAS		
		MERGE DETALLE_ORDENES AS T2 USING (SELECT * FROM HIST_DETALLE_ORDENES 
		WHERE FK_ORDEN IN (SELECT "INDEX" FROM ORDENES_VENTA) 
		AND FK_CLIENTE IN (SELECT ID_CLIENTE FROM CLIENTES)
		AND FK_PRODUCT IN(SELECT ID_PRODUCT FROM PRODUCTOS)
		AND  FORMAT(FECHA_REGISTRO,'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh')
		)  AS T1
			ON T2.FK_ORDEN=T1.FK_ORDEN AND T2.FK_CLIENTE=T1.FK_CLIENTE AND T2.FK_PRODUCT=T1.FK_PRODUCT
			WHEN NOT MATCHED THEN
			INSERT
			(
				CANTIDAD_VENTA,
				MONTO_VENTA,
				MONEDA,
				PROMOTION_IDS,
				FK_ORDEN,
				FK_CLIENTE,
				FK_PRODUCT
			)
			VALUES
			(
				CONVERT(DECIMAL(15,2),T1.CANTIDAD_VENTA),
				CONVERT(DECIMAL(15,2),T1.MONTO_VENTA),
				T1.MONEDA,
				T1.PROMOTION_IDS,
				CONVERT(BIGINT,T1.FK_ORDEN),
				CONVERT(BIGINT,T1.FK_CLIENTE),
				CONVERT(BIGINT,T1.FK_PRODUCT)
			);
	END
	ELSE IF @TABLENAME='INFO'
	BEGIN
		--EXEC SP_CLEAN_DATA_VENTAS
		MERGE INFO_ENTREGAS AS T2 USING (SELECT * FROM HIST_INFO_ENTREGAS WHERE FK_VENTA IN (SELECT "INDEX" FROM ORDENES_VENTA) AND FK_SEPOMEX IN(SELECT ID_ENTIDAD FROM CAT_SEPOMEX) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh'))  AS T1
			ON T2.FK_VENTA=T1.FK_VENTA AND T2.FK_SEPOMEX=T1.FK_SEPOMEX
			WHEN NOT MATCHED THEN
			INSERT
			(
				DIRECCION_FULL,
				FK_SEPOMEX,
				FK_VENTA
			)
			VALUES
			(
				T1.DIRECCION_FULL,
				CONVERT(BIGINT,T1.FK_SEPOMEX),
				CONVERT(BIGINT,T1.FK_VENTA)
			);
	END
	ELSE IF @TABLENAME='ENTREGAS'
	BEGIN
		--EXEC SP_CLEAN_DATA_VENTAS
		MERGE ENTREGAS AS T2 USING (SELECT * FROM HIST_ENTREGAS WHERE FK_ENTREGA_INFO IN (SELECT ID_INFO_ENTREGA FROM INFO_ENTREGAS) AND FORMAT(FECHA_REGISTRO, 'dd/MM/yyyy hh')=FORMAT(GETDATE(), 'dd/MM/yyyy hh'))  AS T1
			ON CONVERT(DATE, T2.FECHA_ENTREGA, 103)=CONVERT(DATE, T1.FECHA_ENTREGA, 103) AND T2.FK_ENTREGA_INFO=T1.FK_ENTREGA_INFO
			WHEN NOT MATCHED THEN
			INSERT
			(
				FECHA_ENTREGA,
				FK_ENTREGA_INFO
			)
			VALUES
			(
				CONVERT(DATE, T1.FECHA_ENTREGA, 103),
				CONVERT(BIGINT,T1.FK_ENTREGA_INFO)
			);
	END
	SELECT 'PROCESO TERMINADO CON EXITO' PROCESO
END TRY
BEGIN CATCH
	SELECT 'PROCESO TERMINADO CON EXITO' PROCESO
	--SELECT CONCAT('ERROR DURANTE EL PROCES: ',ERROR_MESSAGE()) ERROR_MERGE
END CATCH
END
