CREATE OR ALTER PROC SP_PROPERTIES_TABLES
@BANDERA INT=NULL,
@TABLE VARCHAR(50)=NULL
AS
DECLARE @SQL_QUERY AS VARCHAR(MAX)
BEGIN
	IF @BANDERA=0 BEGIN
		select COLUMN_NAME, DATA_TYPE
		from INFORMATION_SCHEMA.COLUMNS
		where TABLE_NAME = @TABLE  AND COLUMN_DEFAULT IS NULL
		order by ORDINAL_POSITION
	END
	ELSE IF @BANDERA=1 BEGIN		----TRUNCA TABLAS
		SET @SQL_QUERY=CONCAT('TRUNCATE TABLE ', @TABLE)
		BEGIN TRY
			EXEC(@SQL_QUERY)
			SELECT '1' CORRECTO
		END TRY
		BEGIN CATCH
			SELECT '0' CORRECTO
		END CATCH
	END
	ELSE IF @BANDERA=2 BEGIN ----REGISTRO DE TABLAS
		SET @SQL_QUERY=CONCAT('SELECT COUNT_BIG(*) CONTEO_FILAS FROM ', @TABLE)
		BEGIN TRY
			EXEC(@SQL_QUERY)
		END TRY
		BEGIN CATCH
			SELECT '0' INCORRECTO
		END CATCH
	END
END
GO
